name: Help Request
description: Request help or report an issue with PrefillPrompt
labels: [help wanted]
body:
    - type: markdown
      attributes:
          value: |
              ### Before you start

              - Check the [existing issues](https://github.com/ThatGuySam/prefillprompt/issues) to see if your problem has already been reported.
              - Make sure you're using the latest version of PrefillPrompt.

              ### Issue etiquette

              When opening an issue, please:
              - Provide as much detail as possible about your problem or question.
              - Include steps to reproduce the issue if applicable.
              - Write your request primarily in English.
              ---
    - type: dropdown
      id: issue-type
      attributes:
          label: Type of Help Request
          description: What kind of help do you need?
          options:
              - Bug Report
              - Feature Request
              - Usage Question
              - Other
      validations:
          required: true
    - type: textarea
      id: description
      attributes:
          label: Describe your problem or question
          description: Provide a clear and concise description of the issue or question you have.
      validations:
          required: true
    - type: textarea
      id: reproduce-steps
      attributes:
          label: Steps to reproduce (if applicable)
          description: If you're reporting a bug, please provide steps to reproduce the issue.
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
              4. See error
    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected behavior
          description: What did you expect to happen?
    - type: textarea
      id: actual-behavior
      attributes:
          label: Actual behavior
          description: What actually happened?
    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: |
              Please provide details about your environment:
              - Operating System:
              - Browser (if applicable):
          placeholder: |
              - Operating System: macOS 12.4
              - Browser: Chrome 101.0.4951.64
    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context, screenshots, or code snippets about your problem here.
